### ISSUE TITLE
Error while validating https://tamn.snapplanet.io/

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stac-api-validator#103]
Got an error while validating https://tamn.snapplanet.io/, in the 'item search' test:

```
Failed.
Error https://tamn.snapplanet.io/: <class 'TypeError'> object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/cholmes/opt/anaconda3/envs/threeten/lib/python3.10/site-packages/stac_api_validator/__main__.py", line 66, in main
    (warnings, errors) = validate_api(
  File "/Users/cholmes/opt/anaconda3/envs/threeten/lib/python3.10/site-packages/stac_api_validator/validations.py", line 221, in validate_api
    validate_item_search(root_body, post, collection, conforms_to, warnings, errors)
  File "/Users/cholmes/opt/anaconda3/envs/threeten/lib/python3.10/site-packages/stac_api_validator/validations.py", line 508, in validate_item_search
    validate_item_search_ids_does_not_override_all_other_params(
  File "/Users/cholmes/opt/anaconda3/envs/threeten/lib/python3.10/site-packages/stac_api_validator/validations.py", line 956, in validate_item_search_ids_does_not_override_all_other_params
    _validate_search_ids_with_ids_no_override(search_url, items[0], post, errors)
  File "/Users/cholmes/opt/anaconda3/envs/threeten/lib/python3.10/site-packages/stac_api_validator/validations.py", line 915, in _validate_search_ids_with_ids_no_override
    if len(r.json().get("features")) > 0:
TypeError: object of type 'NoneType' has no len()
```

I think the validator should be just reporting the problem, not putting out stack traces?

**Comment by philvarner** [comment]
The underlying issue is that snapplanet doesn't support POST, so the POST gets a response that's not an ItemCollection, and that code isn't defensive enough -- I'll put a fix in for that.

**Comment by cholmes** [comment]
Thanks! Will try it out.
